# Calculating body mass
print("What is your name human?")
name = input()
print("How old are you (in years)?")
age = input()
print("How tall are you (in meters)?")
height = float(input())
print("How much do you weight (in kilograms)?")
weight = int(input())
bmi = str(weight / (height**2))
print(name + " you are " + age + " old and your BMI is " + bmi)
